apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-a

bases:
- ../base

patches:
- target:
    kind: Namespace
    name: default-dev
  patch: |-
    - op: replace
      path: /metadata/name
      value: team-a
- target:
    kind: ResourceQuota
    name: resource-quota
  patch: |-
    - op: replace
      path: /spec/hard/limits.cpu
      value: 1 
- target:
    kind: ResourceQuota
    name: resource-quota
  patch: |-
    - op: replace
      path: /spec/hard/services
      value: 10 