apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace }}
spec:
  limits:
  - default:
      cpu: {{ .Values.limits.default.cpu }}
      memory: {{ .Values.limits.default.memory }}
    defaultRequest:
      cpu: {{ .Values.limits.defaultRequest.cpu }}
      memory: {{ .Values.limits.defaultRequest.cpu }}
    type: {{ .Values.limits.type }}
