apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.requests.cpu }}
    requests.memory: {{ .Values.quota.requests.memory }}
    limits.cpu: {{ .Values.quota.limits.cpu }}
    limits.memory: {{ .Values.quota.limits.memory }}
    pods: {{ .Values.quota.pods }}
    persistentvolumeclaims: {{ .Values.quota.persistentvolumeclaims }}
    resourcequotas: {{ .Values.quota.resourcequotas }}
    services: {{ .Values.quota.services }}
