apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-b

bases:
- ../../base

patches:
- target:
    kind: Namespace
    name: default-dev
  patch: |-
    - op: replace
      path: /metadata/name
      value: team-b
- target:
    kind: LimitRange
    name: limit-range
  patch: |-
    - op: replace
      path: /metadata/name
      value: limit-team-b
    - op: replace
      path: /spec/limits/0/defaultRequest/cpu
      value: 150m
- target:
    kind: ResourceQuota
    name: resource-quota
  patch: |-
    - op: replace
      path: /metadata/name
      value: quota-team-b

