apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- resource-quota.yaml
- limit-range.yaml

patchesJson6902:
- patch: |-
    - op: replace
      path: /metadata/name
      value: prod1
  target:    
    kind: Namespace  
    name: dev  
    version: v1
    group: apps