apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- resource-quota.yaml
- limit-range.yaml
- namespace2.yaml

patchesJson6902:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: prod
  target:    
    kind: ResourceQuota  
    name: resource-quota  
    version: v1
    group: apps