apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesJson6902:
- patch: |-
    - op: replace
      path: /metadata/name
      value: prod1
  target:    
    kind: Namespace  
    name: prod  
    version: v1